// AUTO-GENERATED FROM project-documentation validator autogen. DO NOT EDIT BY HAND.
// validator-command-id: 000000028271
// validator-refreshed-at: 2026-08-25T19:07:41-04:00
// validator-refresh-source: foreground-generated-refresh
// Source by-file UID: 0000MQ
// Source by-file doc: by-file/PrimeNumberGenerator.md
// UID:0000AT | by-class/PrimeNumberGenerator.md | Completion:93 | Confidence:92
#include "PrimeNumberGenerator.h"

#include <string.h>

// UID:0001FA | by-memory/0x0054bcc0-0x0054bcec.PrimeNumberGeneratorGetPrimeAt.md | Completion:88 | Confidence:90
int PrimeNumberGenerator::GetPrimeAt(int index) const
{
    if (index < 0)
        return 2;

    if (index >= static_cast<int>(m_primes.size()))
        index = static_cast<int>(m_primes.size()) - 1;

    return m_primes[index];
}

// UID:0001FB | by-memory/0x0054bcf0-0x0054c15a.PrimeNumberGenerator.md | Completion:93 | Confidence:92
PrimeNumberGenerator::PrimeNumberGenerator(int limit)
{
    if (limit < 100)
        limit = 100;
    if (limit > 10000000)
        limit = 10000000;

    m_primes.clear();
    m_primes.push_back(2);
    m_primes.push_back(3);

    unsigned int sieveWordCount =
        static_cast<unsigned int>(limit / 3 + 1);
    m_sieveBits = new unsigned int[sieveWordCount];
    memset(m_sieveBits, 0, sieveWordCount * sizeof(unsigned int));

    for (int upperCandidate = 7;
         upperCandidate <= limit;
         upperCandidate += 6)
    {
        int lowerCandidate = upperCandidate - 2;
        unsigned int lowerIndex =
            static_cast<unsigned int>(lowerCandidate / 3);

        if ((m_sieveBits[lowerIndex >> 5] &
             (1U << (lowerIndex & 31))) == 0)
        {
            m_primes.push_back(lowerCandidate);

            for (int multiple = lowerCandidate;
                 multiple < limit;
                 multiple += lowerCandidate)
            {
                if (multiple % 6 == 1 || multiple % 6 == 5)
                {
                    unsigned int sieveIndex =
                        static_cast<unsigned int>(multiple / 3);
                    m_sieveBits[sieveIndex >> 5] |=
                        1U << (sieveIndex & 31);
                }
            }
        }

        unsigned int upperIndex =
            static_cast<unsigned int>(upperCandidate / 3);

        if ((m_sieveBits[upperIndex >> 5] &
             (1U << (upperIndex & 31))) == 0)
        {
            m_primes.push_back(upperCandidate);

            for (int multiple = upperCandidate;
                 multiple < limit;
                 multiple += upperCandidate)
            {
                if (multiple % 6 == 1 || multiple % 6 == 5)
                {
                    unsigned int sieveIndex =
                        static_cast<unsigned int>(multiple / 3);
                    m_sieveBits[sieveIndex >> 5] |=
                        1U << (sieveIndex & 31);
                }
            }
        }
    }

    delete [] m_sieveBits;
}

PrimeNumberGenerator::~PrimeNumberGenerator()
{
}

// UID:0002OK | by-memory/0x0062241c-0x00622424.PrimeNumberGeneratorVtableData.md | Completion:88 | Confidence:93
// PrimeNumberGenerator RTTI/vtable data is generated by the compiler from the class declaration and virtual destructor layout.
