// AUTO-GENERATED FROM project-documentation validator autogen. DO NOT EDIT BY HAND.
// validator-command-id: 000000028253
// validator-refreshed-at: 2026-08-25T17:55:53-04:00
// validator-refresh-source: foreground-generated-refresh
// Source by-file UID: 0000MP
// Source by-file doc: by-file/PrettyButtonControlPane.md
// UID:0000AR | by-class/PrettyButtonControlPane.md | Completion:92 | Confidence:93
// UID:0004E3 | by-memory/0x0054b5e0-0x0054b6a4.PrettyButtonControlPaneConstructor.md | Completion:90 | Confidence:92
PrettyButtonControlPane::PrettyButtonControlPane(const RectBounds &bounds,
                                                 const wchar_t *epfResourceName,
                                                 const wchar_t *paletteResourceName,
                                                 int normalFrameId,
                                                 int pressedFrameId,
                                                 int selectedFrameId,
                                                 unsigned char constructorFlag)
    : ButtonControlPane(bounds),
      m_normalFrameId(normalFrameId),
      m_pressedFrameId(pressedFrameId),
      m_selectedFrameId(selectedFrameId),
      m_selected(false),
      m_visualStateFrameActive(false),
      m_epfResourceName(epfResourceName),
      m_paletteResourceName(paletteResourceName)
{
    m_controlFlags = constructorFlag;
    m_callback = NULL;
    m_reservedControlState = 0;
}

// UID:0004E4 | by-memory/0x0054b6b0-0x0054b6fb.PrettyButtonControlPaneDestructorBody.md | Completion:88 | Confidence:91
PrettyButtonControlPane::~PrettyButtonControlPane()
{
    delete m_callback;
}

// UID:0004E5 | by-memory/0x0054b700-0x0054b719.PrettyButtonControlPaneStateByteVirtualForwarder.md | Completion:88 | Confidence:91
void PrettyButtonControlPane::SetSelected(bool selected)
{
    m_selected = selected;
    InvalidateRect(NULL);
}

// UID:0004E6 | by-memory/0x0054b720-0x0054b744.PrettyButtonControlPaneSetCallback.md | Completion:88 | Confidence:91
void PrettyButtonControlPane::SetCallback(FunctionObject0 *callback)
{
    delete m_callback;
    m_callback = callback;
}

// UID:0004E7 | by-memory/0x0054b750-0x0054b7b2.PrettyButtonControlPaneSetVisualState.md | Completion:88 | Confidence:91
void PrettyButtonControlPane::SetState(unsigned char state)
{
    if (m_visualState != state)
    {
        if (state == 0x0b)
        {
            m_visualStateFrameActive = true;
            m_timerHandler.ScheduleTimer(0, 150, 0, 0);
        }
        else
        {
            m_visualStateFrameActive = false;
            m_timerHandler.RemovePendingTimers();
        }
    }

    ControlPane::SetVisualState(state);
}

// UID:0004E8 | by-memory/0x0054b7c0-0x0054b879.PrettyButtonControlPaneOnPaint.md | Completion:90 | Confidence:92
int PrettyButtonControlPane::OnPaint()
{
    int frameId = m_normalFrameId;

    if (m_visualStateFrameActive) {
        frameId = m_pressedFrameId;
    } else if (m_selected) {
        frameId = m_selectedFrameId;
    }

    EPFTileContext tileContext;
    tileContext.Init();

    g_pEPFLib->LookupLayoutEntry(m_epfResourceName.c_str(), frameId, &tileContext);

    FrameDrawRecord drawRecord;
    int result = RenderTileFrame(&tileContext,
                                 &drawRecord,
                                 &m_bounds,
                                 1,
                                 m_paletteResourceName.c_str(),
                                 0);

    if (!m_enabled) {
        SetDrawColor(143);
        m_drawMode = 2;
        return g_surfaceRenderCallbacks->PreparePaneRegion(this, &m_bounds);
    }

    return result;
}

// UID:0004E9 | by-memory/0x0054b880-0x0054b8b9.PrettyButtonControlPaneOnClick.md | Completion:87 | Confidence:90
bool PrettyButtonControlPane::OnClick(unsigned int actionId, int, int)
{
    if (actionId <= 1)
    {
        m_timerHandler.ScheduleTimer(1, 150, 0, 0);

        if (m_callback)
            m_callback->Invoke();
    }

    return true;
}

// UID:0002UW | by-memory/0x006222d4-0x00622378.PrettyButtonControlPaneVtableData.md | Completion:90 | Confidence:94
// PrettyButtonControlPane RTTI/vtable data is generated by the compiler from the class declaration and virtual method layout.

// UID:0000AS | by-class/PrettyButtonControlPane2.md | Completion:92 | Confidence:93
// UID:0004EA | by-memory/0x0054b8c0-0x0054b98d.PrettyButtonControlPane2Constructor.md | Completion:89 | Confidence:91
PrettyButtonControlPane2::PrettyButtonControlPane2(const RectBounds &bounds,
                                                   const wchar_t *epfResourceName,
                                                   const wchar_t *paletteResourceName,
                                                   int normalFrameId,
                                                   int pressedFrameId,
                                                   int selectedFrameId,
                                                   int disabledFrameId,
                                                   unsigned char constructorFlag)
    : ButtonControlPane(bounds),
      m_normalFrameId(normalFrameId),
      m_pressedFrameId(pressedFrameId),
      m_selectedFrameId(selectedFrameId),
      m_disabledFrameId(disabledFrameId),
      m_selected(false),
      m_visualStateFrameActive(false),
      m_epfResourceName(epfResourceName),
      m_paletteResourceName(paletteResourceName)
{
    m_controlFlags = constructorFlag;
    m_callback = NULL;
    m_reservedControlState = 0;
}

// UID:0004EB | by-memory/0x0054b990-0x0054b9db.PrettyButtonControlPane2DestructorBody.md | Completion:88 | Confidence:91
PrettyButtonControlPane2::~PrettyButtonControlPane2()
{
    delete m_callback;
}

// UID:0004EC | by-memory/0x0054b9e0-0x0054b9f9.PrettyButtonControlPane2StateByteVirtualForwarder.md | Completion:88 | Confidence:90
void PrettyButtonControlPane2::SetSelected(bool selected)
{
    m_selected = selected;
    InvalidateRect(NULL);
}

// UID:0004ED | by-memory/0x0054ba00-0x0054ba24.PrettyButtonControlPane2SetCallback.md | Completion:88 | Confidence:90
void PrettyButtonControlPane2::SetCallback(FunctionObject0 *callback)
{
    delete m_callback;
    m_callback = callback;
}

// UID:0004EE | by-memory/0x0054ba30-0x0054ba92.PrettyButtonControlPane2SetVisualState.md | Completion:88 | Confidence:91
void PrettyButtonControlPane2::SetState(unsigned char state)
{
    if (m_visualState != state)
    {
        if (state == 0x0b)
        {
            m_visualStateFrameActive = true;
            m_timerHandler.ScheduleTimer(0, 150, 0, 0);
        }
        else
        {
            m_visualStateFrameActive = false;
            m_timerHandler.RemovePendingTimers();
        }
    }

    ControlPane::SetVisualState(state);
}

// UID:0004EF | by-memory/0x0054baa0-0x0054bb48.PrettyButtonControlPane2OnPaint.md | Completion:88 | Confidence:90
int PrettyButtonControlPane2::OnPaint()
{
    int frameId;

    if (!m_enabled) {
        frameId = m_disabledFrameId;
    } else if (m_visualStateFrameActive) {
        frameId = m_pressedFrameId;
    } else if (m_selected) {
        frameId = m_selectedFrameId;
    } else {
        frameId = m_normalFrameId;
    }

    EPFTileContext tileContext;
    tileContext.Init();

    g_pEPFLib->LookupLayoutEntry(m_epfResourceName.c_str(), frameId, &tileContext);

    FrameDrawRecord drawRecord;
    return RenderTileFrame(&tileContext,
                           &drawRecord,
                           &m_bounds,
                           1,
                           m_paletteResourceName.c_str(),
                           0);
}

// UID:0004EG | by-memory/0x0054bb50-0x0054bb89.PrettyButtonControlPane2OnClick.md | Completion:88 | Confidence:91
bool PrettyButtonControlPane2::OnClick(unsigned int action, int x, int y)
{
    if (action <= 1) {
        m_timerHandler.ScheduleTimer(1, 150, 0, 0);
        if (m_callback != NULL)
            m_callback->Invoke();
    }

    return true;
}

// UID:0002UX | by-memory/0x00622378-0x0062241c.PrettyButtonControlPane2VtableData.md | Completion:90 | Confidence:94
// PrettyButtonControlPane2 RTTI/vtable data is generated by the compiler from the class declaration and virtual method layout.
