// AUTO-GENERATED FROM project-documentation validator autogen. DO NOT EDIT BY HAND.
// validator-command-id: 000000028271
// validator-refreshed-at: 2026-08-25T19:07:41-04:00
// validator-refresh-source: foreground-generated-refresh
// Source by-file UID: 0000L2
// Source by-file doc: by-file/MapNamePane.md
// UID:00007P | by-class/MapNamePane.md | Completion:94 | Confidence:95
#include "MapNamePane.h"

#include "../archive/DATFile.h"
#include "../render/ImageLib.h"
#include "../render/Surface.h"
#include "../ui/core/Event.h"
#include "../util/MemoryMan.h"

#include <windows.h>
#include <wchar.h>

extern bool g_useEpfAssets;

// UID:0002BF | by-memory/0x00503110-0x005031e1.WideGlyphResourceTextRendererRaw.md | Completion:92 | Confidence:93
void MapNamePane::DrawNumberGlyphString(
    const wchar_t *text, int x, int y, signed char glyphRow)
{
    EPFTileContext glyphContext;
    glyphContext.rowStridePixels = 9;
    InitRectBounds(&glyphContext.bounds, 0, 0, 9, 11);

    RectBounds destinationBounds;
    InitRectBounds(&destinationBounds, x, y, x + 9, y + 11);

    for (const wchar_t *scan = text; *scan != L'\0'; ++scan)
    {
        if (*scan != L' ' && *scan != L'/')
        {
            const int glyphIndex =
                static_cast<int>(*scan) + glyphRow * 10 - 47;
            glyphContext.pixelData = m_mapNameGlyphs + glyphIndex * 99;
            g_pfnBlitSprite(this,
                            &glyphContext,
                            &glyphContext.bounds,
                            &destinationBounds,
                            1, NULL, NULL);
        }

        OffsetRect(&destinationBounds, 9, 0);
    }
}

// UID:0003XG | by-memory/0x005031f0-0x005032c3.MapNamePaneConstructor.md | Completion:94 | Confidence:95
MapNamePane::MapNamePane()
    : Pane(1)
{
    m_mapNameText[0] = L'\0';

    if (g_useEpfAssets)
    {
        g_pEPFLib->LookupLayoutEntry(
            L"MAPNAME.EPF", 0, &m_mapNameImage);

        int glyphDataSize;
        m_mapNameGlyphs = reinterpret_cast<unsigned char *>(
            LoadDatFileBuffer(L"9X11FONT.BIN", 99, &glyphDataSize));
    }
}

// UID:0003XH | by-memory/0x005032d0-0x0050334d.MapNamePaneNonDeletingDestructor.md | Completion:93 | Confidence:95
MapNamePane::~MapNamePane()
{
    if (m_mapNameGlyphs != NULL)
    {
        m_mapNameGlyphs = static_cast<unsigned char *>(
            GetMemoryMan()->FreeBufferMemory(m_mapNameGlyphs));
    }
}

// UID:0003XI | by-memory/0x00503350-0x0050349f.MapNamePaneOnPaint.md | Completion:94 | Confidence:95
void MapNamePane::OnPaint()
{
    GetMemoryMan();

    const int length = static_cast<unsigned short>(wcslen(m_mapNameText));

    if (g_useEpfAssets)
    {
        RenderTileFrame(&m_mapNameImage,
                        &m_mapNameImage.bounds,
                        &m_mapNameImage.bounds,
                        1, L"FRMPART.PAL", NULL);

        const int x = (m_visibleBounds.left + m_visibleBounds.right) / 2
                    - GetTextWidth(m_mapNameText, length) / 2;
        const int y = (m_visibleBounds.top + m_visibleBounds.bottom) / 2 + 5;
        m_textDrawMode = 1;
        SetTextColor(0x80);
        MoveTo(x + 1, y);
        DrawWideText(m_mapNameText, length);
        MoveTo(x, y);
        DrawWideText(m_mapNameText, length);
    }
    else
    {
        m_drawMode = 0;
        SetDrawColor(0);
        g_pfnFillRect(this, &m_visibleBounds);

        const int x = (m_visibleBounds.left + m_visibleBounds.right) / 2
                    - GetTextWidth(m_mapNameText, length) / 2;
        MoveTo(x, m_visibleBounds.bottom);
        m_textDrawMode = 1;
        SetTextColor(0x8f);
        DrawWideText(m_mapNameText, length);
    }
}

// UID:0003XJ | by-memory/0x005034a0-0x00503574.MapNamePaneHandleMapNameUpdatePacket.md | Completion:94 | Confidence:95
bool MapNamePane::HandlePacketEvent(Event *event)
{
    MemoryMan *memoryMan = GetMemoryMan();
    const unsigned char *packet =
        static_cast<const unsigned char *>(event->m_payload.m_packet.m_data);

    if (packet[0] == 0x15)
    {
        const unsigned char byteCount = packet[9];
        char mapNameBytes[256];
        memoryMan->MemmoveWrapper(mapNameBytes, packet + 10, byteCount);
        mapNameBytes[byteCount] = '\0';

        const unsigned char wideLength = static_cast<unsigned char>(
            MultiByteToWideChar(CP_ACP, 0, mapNameBytes, byteCount,
                                m_mapNameText, 128));
        m_mapNameText[wideLength] = L'\0';
        FitTextAndAppendSuffix(m_mapNameText, 128, L"...", 173);
        InvalidateRect(&m_visibleBounds);
    }

    return false;
}

// UID:0003BZ | by-memory/0x0061e5b4-0x0061e63c.MapNamePaneVtableData.md | Completion:94 | Confidence:97
// MapNamePane vtables and RTTI are generated by the class declaration.

// UID:0003IL | by-memory/0x0061e6c0-0x0061e6d8.MapNamePaneEpfResourceString.md | Completion:93 | Confidence:96
// MAPNAME.EPF is emitted by MapNamePane::MapNamePane() as an inline wide literal.

// UID:0002XC | by-global/g_pMapNamePane.md | Completion:93 | Confidence:95
MapNamePane *g_pMapNamePane = NULL;
